#!/bin/bash -e
git diff --cached --name-only --diff-filter=ACM | while IFS='' read -r line || [[ -n "$line" ]]; do
  if [[ $line == *.ipynb ]] ;
  then
    nb_dir=$(dirname $line)
    if [[ $nb_dir == "." ]]; then
        nb_dir=""
    fi
    filename=$(basename $line)
    stripped_dir=stripped/${nb_dir} #copy the directory structure
    mkdir -p $stripped_dir
    target_stripped_file="${stripped_dir}/${filename%.ipynb}_stripped.py"

    python3 <(cat <<SCRIPT
import json
import sys

data = json.load(sys.stdin)
for cell in data['cells']:
    cell_type = cell['cell_type']
    source = cell['source']
    if cell_type == 'markdown':
        print('"""')
        for line in source:
            print(line.rstrip('\n'))
        print('"""\n')
    elif cell_type == 'code':
        for line in source:
            print(line.rstrip('\n'))
        print('\n')
    else:
        raise ValueError('Cell type', cell_type)
SCRIPT
) <$line >$target_stripped_file

    git add $target_stripped_file
  fi
done
